Fix RtlIsCriticalSectionLockedByThread: add missing C stub + __imp__ pointer
The previous commit stripped the symbol from ntdll.spec and libntdll.a but
forgot to add the actual implementation. This caused Wine 6/7/8 to fail
with undefined reference to `_imp__RtlIsCriticalSectionLockedByThread@4`.